import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Da",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("admin", 8),
      isAdmin: true,
    },

    {
      name: "Duc Anh",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Prosciutto e funghi",
      desc: "It is a pizza variety that is topped with tomato sauce, mozzarella, thin slices of prosciutto cotto, and mushrooms.",
      price: "19.99",
      img: "https://live.staticflickr.com/65535/51425534473_b85917ee1e_o.jpg",
      alt: "pizza-1",
      type: "pizza",
    },
    {
      name: "Pizza fiori di zucca",
      desc: "This is a variety of Italian pizza that is traditionally topped with mozzarella cheese, zucchini flowers, olive oil, and salted anchovies.",
      price: "29.99",
      img: "https://live.staticflickr.com/65535/51424537347_e336de6184_o.jpg",
      alt: "pizza-2",
      type: "pizza",
    },
    {
      name: "Pizza e fichi",
      desc: "Pizza e fichi is a variety of pizza bianca, which is usually topped with mozzarella, garlic, salt, olive oil, and, sometimes, rosemary leaves.",
      price: "19.99",
      img: "https://live.staticflickr.com/65535/51426047054_106e868366_o.jpg",
      alt: "pizza-3",
      type: "pizza",
    },
    {
      name: "Pugliese Pizza",
      desc: "In its simplest form, the basic pizza dough is topped with tomato sauce, mozzarella, and red onion rings.",
      price: "32.99",
      img: "https://live.staticflickr.com/65535/51426047044_5a722d6d65_o.jpg",
      alt: "pizza-4",
      type: "pizza",
    },
    {
      name: "Pizza al padellino",
      desc: "Pizza al padellino is an Italian pizza variety that is baked and served in small, round pans.",
      price: "19.99",
      img: "https://live.staticflickr.com/65535/51426267995_86ded9603f_o.jpg",
      alt: "pizza-5",
      type: "pizza",
    },
    {
      name: "Pizza Romana",
      desc: "The main thing about pizza Romana is its crust: thin, extremely crunchy, and almost cracker-like, which is why it is also known under the name scrocchiarella, meaning the crunchy one.",
      price: "32.99",
      img: "https://live.staticflickr.com/65535/51426046944_d01def5c5d_o.jpg",
      alt: "pizza-6",
      type: "pizza",
    },
    {
      name: "Pizza alla diavola",
      desc: "Diavola is a variety of Italian pizza that is traditionally topped with tomato sauce, mozzarella cheese, spicy salami, and hot chili peppers.",
      price: "22.99",
      img: "https://live.staticflickr.com/65535/51426046939_bba8cb607f_o.jpg",
      alt: "pizza-7",
      type: "pizza",
    },
    {
      name: "Pizza primavera",
      desc: "This Italian pizza variety is prepared with a base of classic pizza dough that is topped with mozzarella and then shortly baked. The fresh ingredients added on top typically include cherry tomatoes, arugula, prosciutto, and parmesan cheese shavings.",
      price: "22.99",
      img: "https://live.staticflickr.com/65535/51424537222_1570c70abf_o.jpg",
      alt: "pizza-8",
      type: "pizza",
    },
    {
      name: "Detroit-Style Pizza",
      desc: "Detroit-style pizza is a square pizza characterized by a thick deep-dish crisp crust and inverted toppings. Cheese is applied directly to the top of the dough, followed by a thick tomato sauce that is seasoned with garlic and spices. The most common topping is pepperoni, put either on top of the sauce or buried underneath the cheese.",
      price: "25.99",
      img: "https://live.staticflickr.com/65535/51426267890_62efeec319_o.jpg",
      alt: "pizza-9",
      type: "pizza",
    },
    {
      name: "Pizza ortolana",
      desc: "The name of this classic Italian pizza translates to greengrocer’s pizza. It consists of a basic pizza dough which is smeared with tomato sauce, topped with mozzarella and grilled slices of eggplant and zucchini, then baked.",
      price: "35.99",
      img: "https://live.staticflickr.com/65535/51426046824_7d25a6ec7e_o.jpg",
      alt: "pizza-10",
      type: "pizza",
    },
    {
      name: "Neapolitan Pizza",
      desc: "Neapolitan is the original pizza. This delicious pie dates all the way back to 18th century in Naples, Italy. During this time, the poorer citizens of this seaside city frequently purchased food that was cheap and could be eaten quickly. Luckily for them, Neapolitan pizza was affordable and readily available through numerous street vendors.",
      price: "19.99",
      img: "https://live.staticflickr.com/65535/51425534468_cd7d2ace98_o.jpg",
      alt: "pizza-11",
      type: "pizza",
    },
    {
      name: "Churros",
      desc: "Elongated, crispy, crunchy and intensely fragrant, churros consist of deep-fried yeast dough encrusted with sugar. Although some may argue against consuming these sweet treats, warning others about the dangerous effects of sugar and fat on human bodies, the popularity of churros throughout the world doesn't seem to wane.",
      price: "9.99",
      img: "https://live.staticflickr.com/65535/51425534753_861ec5b28c_o.jpg",
      alt: "sweet-1",
      type: "sweet",
    },
    {
      name: "Doughlicious",
      desc: "Belgian chocolate glazed donuts covered in icing with sprinkles on top.",
      price: "9.99",
      img: "https://live.staticflickr.com/65535/51425284411_c51a8a481a_o.jpg",
      alt: "sweet-2",
      type: "sweet",
    },
    {
      name: "Caramel Wonder",
      desc: "Vanilla ice cream covered with caramel and chocolate glaze topped with a coco stick.",
      price: "12.99",
      img: "https://live.staticflickr.com/65535/51424537097_c8e383171c_o.jpg",
      alt: "sweet-3",
      type: "sweet",
    },
    {
      name: "Soufflé au chocolat",
      desc: "Chocolate soufflé is an exquisite French dessert that combines dark chocolate with a creamy egg yolk base and fluffy egg whites.",
      price: "12.99",
      img: "https://live.staticflickr.com/65535/51425534678_2f78eddb44_o.jpg",
      alt: "sweet-4",
      type: "sweet",
    },
    {
      name: "Red Velvet Cake",
      desc: "A classic Red Velvet cake made with buttermilk and vinegar for that true Red Velvet cake flavor.",
      price: "12.99",
      img: "https://live.staticflickr.com/65535/51426267755_85717292e5_o.jpg",
      alt: "sweet-5",
      type: "sweet",
    },
    {
      name: "Peanut butter cake",
      desc: "With three layers of thick fudge, chocolate ice cream, peanut butter cup ice cream, and a crunchy pretzel crust, you won’t be able to resist this sweet and salty combination.",
      price: "14.99",
      img: "https://live.staticflickr.com/65535/51425253412_4a4ae0b28b_o.jpg",
      alt: "sweet-6",
      type: "sweet",
    },
    {
      name: "Zitro Quark Mousse",
      desc: "It’s made with delicate lemon cake layers spread with lemon curd, a fluffy whipped cream and lemon curd mousse and topped with lemon jello.",
      price: "10.99",
      img: "https://live.staticflickr.com/65535/51424537022_35cd0e4e82_o.jpg",
      alt: "sweet-7",
      type: "sweet",
    },
    {
      name: "Chocolate-Almond Cake",
      desc: "The cake was drizzled with a simple ganache of semisweet chocolate and coconut milk, and finishes it with fresh raspberries, before serving.",
      price: "9.99",
      img: "https://live.staticflickr.com/65535/51426046679_0241914d72_o.jpg",
      alt: "sweet-8",
      type: "sweet",
    },
    {
      name: "Chocolate Stout Cupcakes",
      desc: "These cupcakes are light in texture but heavy in the chocolate department.",
      price: "6.99",
      img: "https://live.staticflickr.com/65535/51425534543_46abeba3fb_o.jpg",
      alt: "sweet-9",
      type: "sweet",
    },
    {
      name: "Chocolate-Chip Cookies",
      desc: "Bittersweet chocolate and espresso powder create a luscious and balanced batter that stays molten in the center during baking.",
      price: "7.99",
      img: "https://live.staticflickr.com/65535/51426267690_d717c5920c_o.jpg",
      alt: "sweet-10",
      type: "sweet",
    },
    {
      name: "Alton's Chocolate Fudge",
      desc: "This combination of almonds with crunchy toffee and bittersweet chocolate makes a great holiday gift.",
      price: "9.99",
      img: "https://live.staticflickr.com/65535/51424536847_d85abce73a_o.jpg",
      alt: "sweet-11",
      type: "sweet",
    },
  ],
};

export default data;
